# Generated by Django 5.2.6 on 2025-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('milk_alternatives', models.CharField(blank=True, max_length=200)),
                ('preparation_method', models.CharField(default='N/A', max_length=100)),
                ('image', models.ImageField(upload_to='menu/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('preparation_method', models.CharField(default='N/A', max_length=100)),
                ('image', models.ImageField(upload_to='menu/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Toast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('preparation_method', models.CharField(default='N/A', max_length=100)),
                ('image', models.ImageField(upload_to='menu/images/')),
            ],
        ),
    ]
