# Generated by Django 5.2.6 on 2025-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(choices=[('150ml', '150 ml'), ('160ml', '160 ml'), ('240ml', '240 ml'), ('300ml', '300 ml')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='milk_alternatives',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='preparation_method',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='preparation_method',
        ),
        migrations.RemoveField(
            model_name='toast',
            name='preparation_method',
        ),
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='coffee',
            name='temperature',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('both', 'Hot & Cold')], default='hot', max_length=10),
        ),
        migrations.AddField(
            model_name='sweet',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toast',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='toast',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='volume',
            field=models.ManyToManyField(blank=True, to='menu.coffeevolume'),
        ),
    ]
