# Generated by Django 5.2.6 on 2025-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_coffeevolume_remove_coffee_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeevolume',
            name='volume',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
