# Generated by Django 5.2.6 on 2025-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_coffeevolume_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
        migrations.AlterField(
            model_name='toast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
    ]
