# Generated by Django 5.2.6 on 2025-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_sweet_price_toast_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='toast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='toast',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='volume',
            field=models.ManyToManyField(blank=True, related_name='coffees', to='menu.coffeevolume'),
        ),
        migrations.AlterField(
            model_name='coffeevolume',
            name='volume',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='toast',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
