# Generated by Django 5.2.4 on 2025-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_coffee_created_at_coffee_image_coffee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='show_temperature',
            field=models.BooleanField(default=False, help_text='Показувати температуру (hot/iced) в меню'),
        ),
    ]
