# Generated by Django 5.2.4 on 2025-10-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_coffee_show_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='show_temperature',
        ),
    ]
