# Generated by Django 5.2.4 on 2025-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_coffee_show_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='temperature',
            field=models.CharField(blank=True, choices=[('', 'None'), ('hot', 'Hot'), ('cold', 'Cold'), ('both', 'Hot & Cold')], max_length=10, null=True),
        ),
    ]
