# Generated by Django 5.2.4 on 2025-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_coffee_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Друга ціна (опціонально)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Основна ціна', max_digits=8),
        ),
    ]
