# Generated by Django 5.2.6 on 2025-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_coffee_price_2_alter_coffee_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='volume',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='CoffeeVolume',
        ),
    ]
