# Generated by Django 5.2.6 on 2025-10-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_coffee_volume_alter_coffee_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='image',
        ),
        migrations.AddField(
            model_name='coffee',
            name='group',
            field=models.CharField(choices=[('basic', 'Basic Drinks'), ('alternative', 'Alternative'), ('other', 'Other Drinks'), ('addon', 'Add-ons')], default='basic', max_length=20),
        ),
    ]
