# Generated by Django 5.2.4 on 2025-10-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_coffee_image_coffee_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sweet',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toast',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
