# Generated by Django 5.2.4 on 2025-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_coffee_order_sweet_order_toast_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for coffee information modal', null=True),
        ),
    ]
