# Generated by Django 5.2.4 on 2025-10-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_coffee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
