# Generated by Django 5.2.4 on 2025-10-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_coffee_image_alter_coffee_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='toast',
            name='ingredients',
        ),
    ]
